ignoredBuiltDependencies:
  - core-js
  - core-js-pure

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - tree-sitter
  - tree-sitter-json
